-- Crear un esquema
CREATE USER SMART01 IDENTIFIED BY password1234
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Conceder permisos
GRANT CONNECT, RESOURCE TO tienda;