------------------------------------------------------------
-- TABLA: CURRENCIES
------------------------------------------------------------
INSERT INTO SMART01.CURRENCIES (CURRENCY_CODE, NAME, EXPONENT, CREATED_AT) VALUES ('PEN', 'Sol Peruano', 2, TIMESTAMP '2025-10-30 10:55:56');

------------------------------------------------------------
-- TABLA: USERS
------------------------------------------------------------
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT) VALUES (2, 'André Ivan', 'Meléndez Cava', 'andre050719mc@gmail.com', '72193729', '997629981', 'active', null, TIMESTAMP '2025-10-24 16:55:21', DATE '2005-07-19', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT) VALUES (41, 'MIGUEL ALEJANDRO', 'GIRON ALTAMIRANO', 'miguel.girona@unmsm.edu.pe', '74935134', '999280446', 'active', null, TIMESTAMP '2025-11-01 17:04:10', null, null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT) VALUES (1, 'ANDRE IVAN', 'MELENDEZ CAVA', 'andre.melendezc@unmsm.edu.pe', null, null, 'active', null, TIMESTAMP '2025-10-24 16:55:21', null, null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT) VALUES (3, 'ALEJANDRO MANUEL', 'PADILLA ARELLANO', 'alejandro.padillaa@unmsm.edu.pe', '76126506', '910296033', 'active', null, TIMESTAMP '2025-10-24 17:09:40', null, null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (4, 'CARLA', 'FERNÁNDEZ RUIZ', 'carla.fernandez@example.com', '71920220', '981234567', 'active', null, TIMESTAMP '2025-10-29 12:01:30', DATE '1998-03-12', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (5, 'JULIO', 'RAMOS PÉREZ', 'julio.ramos@example.com', '72658731', '912345678', 'active', null, TIMESTAMP '2025-10-29 12:10:12', DATE '1995-11-05', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (6, 'VALERIA', 'TORRES ALVAREZ', 'valeria.torres@example.com', '74890123', '982563410', 'active', null, TIMESTAMP '2025-10-30 09:30:22', DATE '2001-02-18', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (7, 'RODRIGO', 'MENDOZA CASTRO', 'rodrigo.mendoza@example.com', '73124598', '987650432', 'active', null, TIMESTAMP '2025-10-30 10:12:45', DATE '1999-07-21', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (8, 'SOFÍA', 'LÓPEZ CARRASCO', 'sofia.lopez@example.com', '72569831', '998123456', 'active', null, TIMESTAMP '2025-10-31 15:14:05', DATE '2000-09-14', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (9, 'DANIEL', 'QUISPE MAMANI', 'daniel.quispe@example.com', '71458965', '965432187', 'active', null, TIMESTAMP '2025-10-31 16:01:59', DATE '1997-12-25', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (10, 'LUCÍA', 'RAMÍREZ DELGADO', 'lucia.ramirez@example.com', '75410322', '976543210', 'active', null, TIMESTAMP '2025-11-01 10:45:12', DATE '2002-06-10', null);
INSERT INTO SMART01.USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, DNI, PHONE_NUMBER, STATUS, BLOCKED_UNTIL, CREATED_AT, BIRTH_DATE, UPDATED_AT)VALUES (11, 'JORGE', 'FLORES VILLANUEVA', 'jorge.flores@example.com', '73690544', '994512678', 'active', null, TIMESTAMP '2025-11-01 12:02:34',

------------------------------------------------------------
-- TABLA: HOSTS
------------------------------------------------------------
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (41, 'Miguel', 1, 4.00, 10, TIMESTAMP '2025-11-01 17:24:18', TIMESTAMP '2025-11-01 17:24:18');
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (2, null, 0, 0.00, 0, TIMESTAMP '2025-10-24 20:57:13', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (3, null, 0, 0.00, 0, TIMESTAMP '2025-10-27 23:05:54', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (4, 'Carla - Anfitriona en Cusco con cabañas rurales.', 1, 4.5, 42, TIMESTAMP '2025-10-29 12:01:30', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (5, 'Julio - Propietario de varios departamentos en Lima.', 0, 4.1, 16, TIMESTAMP '2025-10-29 12:10:12', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (6, 'Valeria - Superhost de alojamientos modernos en Miraflores.', 1, 4.9, 87, TIMESTAMP '2025-10-30 09:30:22', TIMESTAMP '2025-11-01 10:00:00');
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (7, 'Rodrigo - Anfitrión en Arequipa, especializado en lofts con vista.', 1, 4.7, 51, TIMESTAMP '2025-10-30 10:12:45', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (8, 'Sofía - Anfitriona en Piura con casas frente al mar.', 0, 4.3, 22, TIMESTAMP '2025-10-31 15:14:05', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (9, 'Daniel - Propietario en Puno con habitaciones con vista al Titicaca.', 1, 4.6, 38, TIMESTAMP '2025-10-31 16:01:59', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (10, 'Lucía - Superhost en Trujillo, especialista en alquiler vacacional.', 1, 4.8, 65, TIMESTAMP '2025-11-01 10:45:12', TIMESTAMP '2025-11-02 09:20:00');
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (11, 'Jorge - Anfitrión con propiedades familiares en Huancayo.', 0, 4.2, 19, TIMESTAMP '2025-11-01 12:02:34', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (12, 'María - Propietaria de bungalows ecológicos en Tarapoto.', 1, 4.9, 74, TIMESTAMP '2025-11-01 14:19:20', null);
INSERT INTO SMART01.HOSTS (HOST_ID, DESCRIPTION, IS_VERIFIED, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT)VALUES (13, 'Pablo - Anfitrión de casas rurales en Cajamarca.', 0, 4.4, 33, TIMESTAMP '2025-11-01 16:47:05', null);

------------------------------------------------------------
-- TABLA: AMENITIES
------------------------------------------------------------
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (27, 'AC', 'Aire acondicionado', 'Sistema de aire acondicionado disponible en la propiedad.', null, TIMESTAMP '2025-11-01 16:35:19');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (28, 'WIFI', 'Wifi', 'Conexión inalámbrica a internet de alta velocidad.', null, TIMESTAMP '2025-11-01 16:35:19');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (29, 'TV', 'Televisor', 'Televisor con acceso a canales por cable o streaming.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (30, 'KITCHEN', 'Cocina', 'Espacio equipado con utensilios y electrodomésticos para cocinar.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (31, 'GYM', 'Gimnasio', 'Acceso a instalaciones o equipos de entrenamiento físico.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (32, 'POOL', 'Piscina', 'Piscina privada o compartida disponible para los huéspedes.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (33, 'WASHER', 'Lavadora', 'Lavadora disponible para uso de los huéspedes.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (34, 'DRYER', 'Secadora', 'Secadora eléctrica o de gas disponible para la ropa.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (35, 'HEATING', 'Calefacción', 'Sistema de calefacción para mantener un ambiente cálido.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (36, 'WORKSPACE', 'Zona de trabajo', 'Espacio adecuado con escritorio y silla para trabajar.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (37, 'HAIR_DRYER', 'Secadora de pelo', 'Secadora de cabello disponible en el baño.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (38, 'IRON', 'Plancha', 'Plancha y tabla disponibles para uso doméstico.', null, TIMESTAMP '2025-11-01 16:35:20');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (39, 'JACUZZI', 'Jacuzzi', 'Bañera o tina de hidromasaje para relajación.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (40, 'PARKING', 'Estacionamiento gratuito', 'Espacio gratuito de estacionamiento disponible en el lugar.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (41, 'EV_CHARGER', 'Cargador para autos eléctricos', 'Punto de carga disponible para vehículos eléctricos.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (42, 'CRIB', 'Cuna', 'Cuna o cama pequeña disponible para bebés.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (43, 'KING_BED', 'Cama King', 'Cama tamaño king para mayor comodidad.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (44, 'BBQ', 'Parrilla', 'Área o equipo para parrillas y asados al aire libre.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (45, 'BREAKFAST', 'Desayuno', 'Servicio o provisión de desayuno incluido.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (46, 'FIREPLACE', 'Chimenea interior', 'Chimenea disponible en el interior del alojamiento.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (47, 'SMOKING', 'Apto para fumadores', 'La propiedad permite fumar en ciertas áreas.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (48, 'BEACHFRONT', 'Línea de playa', 'Propiedad ubicada frente al mar o la playa.', null, TIMESTAMP '2025-11-01 16:35:21');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (49, 'COAST', 'Costa', 'Propiedad situada en una zona costera o cercana al mar.', null, TIMESTAMP '2025-11-01 16:35:22');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (50, 'SKI_ACCESS', 'Acceso a pistas de esquí', 'Acceso directo o cercano a zonas de esquí.', null, TIMESTAMP '2025-11-01 16:35:22');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (51, 'SMOKE_DETECTOR', 'Detector de humo', 'Dispositivo para detectar humo y prevenir incendios.', null, TIMESTAMP '2025-11-01 16:35:22');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (52, 'CO_DETECTOR', 'Detector de monóxido de carbono', 'Sensor de seguridad que alerta sobre gases tóxicos.', null, TIMESTAMP '2025-11-01 16:35:22');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (53, 'PETS_ALLOWED', 'Se permiten mascotas', 'La propiedad acepta mascotas bajo ciertas condiciones o previa consulta.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (54, 'SMOKING_ALLOWED', 'Se permite fumar', 'El alojamiento permite fumar en áreas designadas.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (55, 'PARTIES_ALLOWED', 'Se permiten fiestas', 'Se permiten eventos o reuniones dentro de la propiedad.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (56, 'FAMILY_FRIENDLY', 'Apto para niños', 'El alojamiento es adecuado y seguro para familias con niños.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (57, 'BABY_FRIENDLY', 'Apto para bebés', 'Cuenta con condiciones o equipamiento apto para bebés (como cuna o silla alta).', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (58, 'WHEELCHAIR_ACCESSIBLE', 'Acceso para silla de ruedas', 'La propiedad cuenta con rampas, ascensores o accesos adaptados.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (59, 'PARKING_AVAILABLE', 'Hay estacionamiento', 'La propiedad dispone de espacios de estacionamiento disponibles para los huéspedes.', null, TIMESTAMP '2025-11-01 16:43:38');
INSERT INTO SMART01.AMENITIES (AMENITY_ID, CODE, NAME, DESCRIPTION, DISPLAY_ORDER, CREATED_AT) VALUES (60, 'QUIET_HOURS', 'Horario de silencio', 'Se aplican horarios de silencio para mantener la tranquilidad del alojamiento.', null, TIMESTAMP '2025-11-01 16:43:39');

------------------------------------------------------------
-- TABLA: PROPERTIES
------------------------------------------------------------
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT) VALUES (28, 41, 'Departamento moderno en Miraflores', 'Departamento', 250.00, 'PEN', 'Av. Larco 1234, Miraflores', 'Av. Larco 1234, Miraflores, Lima, Perú', 'Lima', 'Lima', 'Perú', '15074', -12.120134, -77.030243, 'ACTIVE', TIMESTAMP '2025-11-01 17:24:55');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT) VALUES (29, 41, 'Casa colonial con patio en Cusco', 'Casa', 180.00, 'PEN', 'Calle Siete Cuartones 365, Centro Histórico', 'Calle Siete Cuartones 365, Cusco, Perú', 'Cusco', 'Cusco', 'Perú', '08002', -13.517088, -71.978535, 'ACTIVE', TIMESTAMP '2025-11-01 17:25:07');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT) VALUES (30, 41, 'Loft minimalista con vista al Misti', 'Loft', 210.00, 'PEN', 'Av. Ejército 1020, Yanahuara', 'Av. Ejército 1020, Yanahuara, Arequipa, Perú', 'Arequipa', 'Arequipa', 'Perú', '04017', -16.386672, -71.539507, 'ACTIVE', TIMESTAMP '2025-11-01 17:25:27');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT) VALUES (1, 3, 'Departamento con vista al parque Kennedy', 'apartment', 250.00, 'PEN', 'Av. Pardo y Aliaga 650', 'Av. Pardo y Aliaga 650, San Isidro, Lima, Perú', 'Lima', 'Lima Metropolitana', 'Perú', '15073', -12.103510, -77.035330, 'ACTIVE', TIMESTAMP '2025-10-31 15:43:51');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT)VALUES (28, 41, 'Departamento moderno en Miraflores', 'Departamento', 250.00, 'PEN', 'Av. Larco 1234, Miraflores', 'Av. Larco 1234, Miraflores, Lima, Perú', 'Lima', 'Lima', 'Perú', '15074', -12.120134, -77.030243, 'ACTIVE', TIMESTAMP '2025-11-01 17:24:55');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT)VALUES (29, 41, 'Casa colonial con patio en Cusco', 'Casa', 180.00, 'PEN', 'Calle Siete Cuartones 365, Centro Histórico', 'Calle Siete Cuartones 365, Cusco, Perú', 'Cusco', 'Cusco', 'Perú', '08002', -13.517088, -71.978535, 'ACTIVE', TIMESTAMP '2025-11-01 17:25:07');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT)VALUES (30, 41, 'Loft minimalista con vista al Misti', 'Loft', 210.00, 'PEN', 'Av. Ejército 1020, Yanahuara', 'Av. Ejército 1020, Yanahuara, Arequipa, Perú', 'Arequipa', 'Arequipa', 'Perú', '04017', -16.386672, -71.539507, 'ACTIVE', TIMESTAMP '2025-11-01 17:25:27');
INSERT INTO SMART01.PROPERTIES (PROPERTY_ID, HOST_ID, TITLE, PROPERTY_TYPE, BASE_PRICE_NIGHT, CURRENCY_CODE, ADDRESS_TEXT, FORMATTED_ADDRESS, CITY, STATE_REGION, COUNTRY, POSTAL_CODE, LATITUDE, LONGITUDE, STATUS, CREATED_AT)VALUES (1, 3, 'Departamento con vista al parque Kennedy', 'apartment', 250.00, 'PEN', 'Av. Pardo y Aliaga 650', 'Av. Pardo y Aliaga 650, San Isidro, Lima, Perú', 'Lima', 'Lima Metropolitana', 'Perú', '15073', -12.103510, -77.035330, 'ACTIVE', TIMESTAMP '2025-10-31 15:43:51');

------------------------------------------------------------
-- TABLA: PROPERTY_DETAILS
------------------------------------------------------------
INSERT INTO SMART01.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT) VALUES (28, 'Amplio departamento moderno con vista al mar, ideal para familias o viajeros de negocios.
   Incluye cocina equipada, sala con TV inteligente y balcón privado.
   Ubicado cerca de restaurantes, supermercados y el Malecón de Miraflores.', 'No se permiten fiestas. No fumar en el interior.
   Mascotas pequeñas bajo solicitud. Check-in solo con documento de identidad.', '14:00', '11:00', 4, 2, 1, 2, 85, 8, TIMESTAMP '2025-11-01 17:34:23', TIMESTAMP '2025-11-01 17:34:23');
INSERT INTO SMART01.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT) VALUES (29, 'Casa de estilo colonial con patio interior, paredes de adobe y techos de madera.
   Perfecta para disfrutar del centro histórico de Cusco con todas las comodidades modernas.
   A pocos minutos de la Plaza de Armas y museos principales.', 'No fumar dentro de la propiedad.
   Mantener silencio a partir de las 22:00.
   Check-in con documento válido. No se permiten eventos.', '13:00', '10:00', 6, 3, 2, 4, 120, 1, TIMESTAMP '2025-11-01 17:34:27', TIMESTAMP '2025-11-01 17:34:27');
INSERT INTO SMART01.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT) VALUES (30, 'Loft moderno y minimalista con ventanales panorámicos hacia el volcán Misti.
   Espacio ideal para parejas o viajeros solitarios.
   Cuenta con cocina americana, smart TV, y Wi-Fi de alta velocidad.', 'No se permiten mascotas.
   No fumar.
   No se permiten visitas no registradas.
   Check-in automatizado con código de acceso.', '15:00', '11:00', 2, 1, 1, 1, 55, 5, TIMESTAMP '2025-11-01 17:34:45', TIMESTAMP '2025-11-01 17:34:45');
INSERT INTO SMART01.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT) VALUES (1, 'Un departamento completo en el corazón de San Isidro, perfecto para ejecutivos o parejas. Totalmente amoblado, con balcón y vista al parque.', 'No se permiten mascotas. No fumar. Por favor, mantenga el ruido al mínimo después de las 10 PM.', '14:00', '11:00', 3, 2, 2, 2, 30, 2, TIMESTAMP '2025-10-31 15:47:41', null);

------------------------------------------------------------
-- TABLA: PROPERTY_AMENITIES
------------------------------------------------------------
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 27);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 28);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 29);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 30);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 32);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 33);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 35);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 36);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 40);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 43);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (28, 53);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 28);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 29);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 30);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 33);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 35);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 36);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 37);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 40);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 45);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 46);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (29, 54);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 27);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 28);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 29);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 30);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 35);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 36);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 40);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 43);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 49);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 51);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 56);
INSERT INTO SMART01.PROPERTY_AMENITIES (PROPERTY_ID, AMENITY_ID) VALUES (30, 57);


------------------------------------------------------------
-- TABLA: BOOKINGS
------------------------------------------------------------
INSERT INTO SMART01.BOOKINGS (BOOKING_ID, PROPERTY_ID, TENANT_ID, CHECKIN_DATE, CHECKOUT_DATE, GUEST_COUNT, CURRENCY_CODE, NIGHT_COUNT, PRICE_NIGHTS, CLEANING_FEE, SERVICE_FEE, TAXES, TOTAL_AMOUNT, STATUS, CREATED_AT, ACCEPTED_AT, DECLINED_AT, COMPLETED_AT, CHECKIN_CODE, HOST_NOTE, TENANT_NOTE) VALUES (1, 28, 1, DATE '2025-09-20', DATE '2025-09-23', 2, 'PEN', 3, 250.00, 40.00, 20.00, 30.00, 840.00, 'COMPLETED', TIMESTAMP '2025-09-22 17:57:31', TIMESTAMP '2025-09-23 17:57:31', null, TIMESTAMP '2025-09-26 17:57:31', 'CHK28A1', null, null);
INSERT INTO SMART01.BOOKINGS (BOOKING_ID, PROPERTY_ID, TENANT_ID, CHECKIN_DATE, CHECKOUT_DATE, GUEST_COUNT, CURRENCY_CODE, NIGHT_COUNT, PRICE_NIGHTS, CLEANING_FEE, SERVICE_FEE, TAXES, TOTAL_AMOUNT, STATUS, CREATED_AT, ACCEPTED_AT, DECLINED_AT, COMPLETED_AT, CHECKIN_CODE, HOST_NOTE, TENANT_NOTE) VALUES (2, 29, 2, DATE '2025-09-10', DATE '2025-09-13', 4, 'PEN', 3, 180.00, 35.00, 15.00, 25.00, 635.00, 'COMPLETED', TIMESTAMP '2025-09-12 17:57:42', TIMESTAMP '2025-09-13 17:57:42', null, TIMESTAMP '2025-09-16 17:57:42', 'CHK29A2', null, null);
INSERT INTO SMART01.BOOKINGS (BOOKING_ID, PROPERTY_ID, TENANT_ID, CHECKIN_DATE, CHECKOUT_DATE, GUEST_COUNT, CURRENCY_CODE, NIGHT_COUNT, PRICE_NIGHTS, CLEANING_FEE, SERVICE_FEE, TAXES, TOTAL_AMOUNT, STATUS, CREATED_AT, ACCEPTED_AT, DECLINED_AT, COMPLETED_AT, CHECKIN_CODE, HOST_NOTE, TENANT_NOTE) VALUES (3, 30, 3, DATE '2025-09-25', DATE '2025-09-28', 2, 'PEN', 3, 210.00, 30.00, 15.00, 20.00, 695.00, 'COMPLETED', TIMESTAMP '2025-09-27 17:57:50', TIMESTAMP '2025-09-28 17:57:50', null, TIMESTAMP '2025-10-01 17:57:50', 'CHK30A3', null, null);

------------------------------------------------------------
-- TABLA: PROPERTY_IMAGES
------------------------------------------------------------
INSERT INTO SMART01.PROPERTY_IMAGES (IMAGE_ID, PROPERTY_ID, URL, CAPTION, SORT_ORDER) VALUES (1, 28, 'https://d1m7bwa5z2c7c9.cloudfront.net/6YOWkcCaxTz_1280x720.jpeg', 'Vista principal del departamento moderno en Miraflores con vista al mar.', 0);
INSERT INTO SMART01.PROPERTY_IMAGES (IMAGE_ID, PROPERTY_ID, URL, CAPTION, SORT_ORDER) VALUES (2, 29, 'https://img.trovit.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMTk3YWRmNi00M2I2LTdkMTEtODk1MS00NmFhOGU0MjMzMTQvYTU3NDQzZjFjOTkxMTJmYmFjZmI2N2EwZTg4ODUxODBiMmQ2NWY2NTg1NTEwZjNjNGU4MDVjMDMyOTc3NmM5YS5qcGVnIiwiYnJhbmQiOiJ0cm92aXQiLCJlZGl0cyI6eyJyb3RhdGUiOm51bGwsInJlc2l6ZSI6eyJ3aWR0aCI6MzYwLCJoZWlnaHQiOjI3MCwiZml0IjoiY292ZXIifX19', 'Casa colonial con patio interior y fachada tradicional del centro de Cusco.', 0);
INSERT INTO SMART01.PROPERTY_IMAGES (IMAGE_ID, PROPERTY_ID, URL, CAPTION, SORT_ORDER) VALUES (3, 30, 'https://pics.nuroa.com/alquiler_de_departamento_en_surquillo_amoblado_3_dormitorios_3260001754755685968.jpg', 'Loft minimalista con vista panorámica del volcán Misti en Arequipa.', 0);
INSERT INTO SMART01.PROPERTY_IMAGES (IMAGE_ID, PROPERTY_ID, URL, CAPTION, SORT_ORDER) VALUES (21, 1, 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTQxNTQ1NjA1OTg2ODMwMzk3MQ==/original/4ca1d7de-94ef-4b75-8b8d-ab3196ef2b1a.jpeg?im_w=1440', 'Departamento luminoso junto al parque Kennedy', 0);
INSERT INTO SMART01.PROPERTY_IMAGES (IMAGE_ID, PROPERTY_ID, URL, CAPTION, SORT_ORDER) VALUES (22, 1, 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTQxNTQ1NjA1OTg2ODMwMzk3MQ==/original/38f7dc9d-04b1-447a-a666-5e059ab6121b.jpeg?im_w=1440', 'Departamento luminoso junto al parque Kennedy', 1);

------------------------------------------------------------
-- TABLA: REVIEWS
------------------------------------------------------------
INSERT INTO SMART01.REVIEWS (REVIEW_ID, BOOKING_ID, PROPERTY_ID, AUTHOR_USER_ID, TARGET_USER_ID, FOR_HOST, RATING, "comment", CREATED_AT, PUBLISHABLE_AT, PUBLISHED_AT, IS_PUBLISHED) VALUES (1, 1, 28, 1, 41, 0, 5, 'Excelente departamento con vista al mar. Limpio, moderno y muy bien ubicado en Miraflores.', TIMESTAMP '2025-10-27 18:02:05', TIMESTAMP '2025-10-28 18:02:05', TIMESTAMP '2025-10-28 18:02:05', 1);
INSERT INTO SMART01.REVIEWS (REVIEW_ID, BOOKING_ID, PROPERTY_ID, AUTHOR_USER_ID, TARGET_USER_ID, FOR_HOST, RATING, "comment", CREATED_AT, PUBLISHABLE_AT, PUBLISHED_AT, IS_PUBLISHED) VALUES (2, 2, 29, 2, 41, 0, 4, 'Hermosa casa colonial con todos los servicios. Muy cerca del centro histórico y con excelente desayuno.', TIMESTAMP '2025-10-29 18:02:10', TIMESTAMP '2025-10-30 18:02:10', TIMESTAMP '2025-10-30 18:02:10', 1);
INSERT INTO SMART01.REVIEWS (REVIEW_ID, BOOKING_ID, PROPERTY_ID, AUTHOR_USER_ID, TARGET_USER_ID, FOR_HOST, RATING, "comment", CREATED_AT, PUBLISHABLE_AT, PUBLISHED_AT, IS_PUBLISHED) VALUES (3, 3, 30, 3, 41, 0, 5, 'El loft es espectacular. Muy limpio, moderno y con una vista impresionante del volcán Misti.', TIMESTAMP '2025-10-31 18:02:14', TIMESTAMP '2025-11-01 18:02:14', TIMESTAMP '2025-11-01 18:02:14', 1);

------------------------------------------------------------
-- TABLA: TENANTS
------------------------------------------------------------
INSERT INTO SMART01.TENANTS (TENANT_ID, BIO, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (41, null, 0.00, 0, TIMESTAMP '2025-11-01 17:04:10', null);
INSERT INTO SMART01.TENANTS (TENANT_ID, BIO, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (2, null, null, 0, TIMESTAMP '2025-10-24 16:55:21', null);
INSERT INTO SMART01.TENANTS (TENANT_ID, BIO, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (1, null, null, 0, TIMESTAMP '2025-10-24 16:55:21', null);
INSERT INTO SMART01.TENANTS (TENANT_ID, BIO, AVERAGE_RATING, REVIEWS_COUNT, CREATED_AT, UPDATED_AT) VALUES (3, null, null, 0, TIMESTAMP '2025-10-24 17:09:40', null);


INSERT INTO SMART01.USER_AUTH_IDENTITIES (IDENTITY_ID, USER_ID, PROVIDER, PROVIDER_USER_ID, EMAIL, EMAIL_VERIFIED, PASSWORD_HASH, LAST_LOGIN_AT, CREATED_AT) VALUES (7, 2, 'google', '106321800302036578422', 'andre050719mc@gmail.com', 1, null, TIMESTAMP '2025-11-03 19:54:11', TIMESTAMP '2025-10-24 19:18:14');
INSERT INTO SMART01.USER_AUTH_IDENTITIES (IDENTITY_ID, USER_ID, PROVIDER, PROVIDER_USER_ID, EMAIL, EMAIL_VERIFIED, PASSWORD_HASH, LAST_LOGIN_AT, CREATED_AT) VALUES (3, 3, 'google', '106579678700230561391', 'alejandro.padillaa@unmsm.edu.pe', 1, null, TIMESTAMP '2025-11-03 23:58:04', TIMESTAMP '2025-10-24 17:09:40');
INSERT INTO SMART01.USER_AUTH_IDENTITIES (IDENTITY_ID, USER_ID, PROVIDER, PROVIDER_USER_ID, EMAIL, EMAIL_VERIFIED, PASSWORD_HASH, LAST_LOGIN_AT, CREATED_AT) VALUES (5, 1, 'google', '117991194155834599269', 'andre.melendezc@unmsm.edu.pe', 1, null, TIMESTAMP '2025-11-03 23:58:02', TIMESTAMP '2025-10-24 17:18:03');

