INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (1, 'Comodidades del Alojamiento');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (2, 'Servicios del Hogar');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (3, 'Bienestar y Recreación');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (4, 'Seguridad');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (5, 'Accesibilidad');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (6, 'Niños y Familias');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (7, 'Políticas de Uso');
INSERT INTO SMART.AMENITIES_CATEGORIES (CATEGORY_ID, NAME) VALUES (8, 'Ubicación y Entorno');
