INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (1, 30, null, 'open', TIMESTAMP '2025-12-01 03:21:21', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (2, 30, null, 'open', TIMESTAMP '2025-12-01 03:21:31', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (6, 54, null, 'open', TIMESTAMP '2025-12-01 03:53:27', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (7, 28, null, 'open', TIMESTAMP '2025-12-01 18:35:42', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (3, 30, null, 'open', TIMESTAMP '2025-12-01 03:23:55', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (5, 30, null, 'open', TIMESTAMP '2025-12-01 03:26:11', null);
INSERT INTO SMART.CONVERSATIONS (CONVERSATION_ID, PROPERTY_ID, BOOKING_ID, STATUS, CREATED_AT, CLOSED_AT) VALUES (4, 30, null, 'open', TIMESTAMP '2025-12-01 03:24:37', null);
