INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (28, 'Amplio departamento moderno con vista al mar, ideal para familias o viajeros de negocios.
   Incluye cocina equipada, sala con TV inteligente y balcón privado.
   Ubicado cerca de restaurantes, supermercados y el Malecón de Miraflores.', 'No se permiten fiestas. No fumar en el interior.
   Mascotas pequeñas bajo solicitud. Check-in solo con documento de identidad.', '14:00', '11:00', 4, 2, 1, 2, 85, 8, TIMESTAMP '2025-11-01 17:34:23', TIMESTAMP '2025-11-01 17:34:23', 2, 2, 2, 2);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (29, 'Casa de estilo colonial con patio interior, paredes de adobe y techos de madera.
   Perfecta para disfrutar del centro histórico de Cusco con todas las comodidades modernas.
   A pocos minutos de la Plaza de Armas y museos principales.', 'No fumar dentro de la propiedad.
   Mantener silencio a partir de las 22:00.
   Check-in con documento válido. No se permiten eventos.', '13:00', '10:00', 6, 3, 2, 4, 120, 1, TIMESTAMP '2025-11-01 17:34:27', TIMESTAMP '2025-11-01 17:34:27', 3, 3, 3, 3);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (30, 'Loft moderno y minimalista con ventanales panorámicos hacia el volcán Misti.
   Espacio ideal para parejas o viajeros solitarios.
   Cuenta con cocina americana, smart TV, y Wi-Fi de alta velocidad.', 'No se permiten mascotas.
   No fumar.
   No se permiten visitas no registradas.
   Check-in automatizado con código de acceso.', '15:00', '11:00', 2, 1, 1, 1, 55, 5, TIMESTAMP '2025-11-01 17:34:45', TIMESTAMP '2025-11-01 17:34:45', 4, 4, 4, 4);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (41, 'Luminoso departamento con cocina equipada, balcón con vista al mar y áreas comunes con piscina.', 'No se permiten fiestas. No fumar. No mascotas.', '15:00', '11:00', 3, 1, 1, 1, 65, 5, TIMESTAMP '2025-11-08 17:51:41', TIMESTAMP '2025-11-08 17:51:41', null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (42, 'Casa amplia con jardín, tres dormitorios, estacionamiento y área de parrilla. Ideal para familias grandes.', 'No fumar en el interior. Se permiten mascotas. Cuidar las áreas verdes.', '14:00', '11:00', 6, 3, 2, 4, 160, 1, TIMESTAMP '2025-11-08 18:11:12', TIMESTAMP '2025-11-08 18:11:12', null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (1, 'Un departamento completo en el corazón de San Isidro, perfecto para ejecutivos o parejas. Totalmente amoblado, con balcón y vista al parque.', 'No se permiten mascotas. No fumar. Por favor, mantenga el ruido al mínimo después de las 10 PM.', '14:00', '11:00', 1, 1, 1, 1, 30, 2, TIMESTAMP '2025-10-31 15:47:41', null, 1, 1, 1, 1);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (43, 'Departamento con vista lateral al mar, cocina americana y sala con TV. Ideal para escapadas cortas.', 'No fumar. No fiestas. Mascotas no permitidas.', '14:00', '11:00', 2, 1, 1, 1, 50, 6, TIMESTAMP '2025-11-08 20:36:41', TIMESTAMP '2025-11-08 20:36:41', null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (80, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 16:10:24', null, 4, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (81, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 16:43:43', null, 4, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (82, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 17:22:23', null, 4, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (59, 'Hermosa casa colonial construida sobre muros incas en pleno centro histórico de Cuzco. Arquitectura tradicional cusqueña con patio central, balcones de madera tallada y vista a la Plaza de Armas. A pasos de la Piedra de los 12 Ángulos y principales atractivos turísticos.', 'No fumar en interiores. Mascotas no permitidas. Respetar el patrimonio histórico del inmueble. Considerar la altitud (3,400 msnm).', '14:00', '11:00', 6, 3, 2, 4, null, null, TIMESTAMP '2025-11-25 03:08:43', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (60, 'Departamento moderno en el barrio bohemio de San Blas, conocido por sus artesanos y galerías de arte. Vista panorámica de los tejados de Cuzco. Cerca de restaurantes, cafés y talleres artesanales. Diseño contemporáneo con toques andinos.', 'No se permiten mascotas. No fumar. Calefacción incluida.', '15:00', '12:00', 4, 2, 2, 2, null, null, TIMESTAMP '2025-11-25 03:09:09', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (61, 'Loft de diseño contemporáneo en Wanchaq, cerca de la estación de tren a Machu Picchu. Ideal para viajeros que planean visitar el Valle Sagrado. Espacio amplio con decoración moderna y funcional. Acceso fácil a supermercados y transporte.', 'Se permiten mascotas pequeñas. No fumar en interiores. Horario de silencio después de las 10 PM.', '14:00', '11:00', 3, 1, 1, 2, null, null, TIMESTAMP '2025-11-25 03:09:26', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (62, 'Hermosa casa campestre en el Valle Sagrado de los Incas, rodeada de montañas y campos de cultivo. Jardines amplios, zona de fogata y vistas espectaculares. Perfecta para familias o grupos que buscan tranquilidad y conexión con la naturaleza. A 1 hora de Cuzco y 30 minutos de Ollantaytambo.', 'Se permiten mascotas. No fumar en interiores. Capacidad máxima 8 personas. Clima templado todo el año.', '15:00', '12:00', 8, 4, 3, 5, null, null, TIMESTAMP '2025-11-25 03:09:43', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (44, 'Estudio funcional y acogedor en San Miguel, cerca de la Costa Verde. Perfecto para viajeros individuales o parejas. Incluye cocina equipada y zona de trabajo. Excelente conexión de transporte.', 'No se permiten mascotas. No fumar. Check-in flexible con previo aviso.', '13:00', '11:00', 2, 1, 1, 1, null, null, TIMESTAMP '2025-11-25 00:30:58', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (46, 'Espectacular penthouse de lujo en San Borja con terraza de 80m2, jacuzzi privado y vista panorámica de Lima. Acabados de primera calidad, domótica completa, cocina gourmet y 3 estacionamientos. Ideal para ejecutivos o familias que buscan lo mejor.', 'No fumar en interiores. Mascotas no permitidas. Uso de jacuzzi hasta las 10 PM. Servicio de limpieza incluido cada 3 días.', '16:00', '12:00', 6, 3, 3, 4, null, null, TIMESTAMP '2025-11-25 00:32:25', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (47, 'Amplio departamento familiar en zona residencial de Surco. Cerca de colegios, parques y centros comerciales. Edificio con áreas comunes: piscina, gimnasio y salón de juegos. Perfecto para estadías largas.', 'Se permiten mascotas pequeñas. No fumar. Uso de áreas comunes según reglamento del edificio.', '14:00', '11:00', 5, 2, 2, 3, null, null, TIMESTAMP '2025-11-25 00:32:43', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (48, 'Apartamento céntrico en Jesús María, zona tranquila y segura. A minutos del centro de Lima y bien conectado con transporte público. Ideal para viajeros de negocios o turistas que buscan comodidad y ubicación.', 'No se permiten mascotas. No fumar. Horario de silencio de 10 PM a 8 AM.', '14:00', '10:00', 3, 1, 1, 2, null, null, TIMESTAMP '2025-11-25 00:33:00', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (50, 'Hermosa casa colonial de sillar en pleno centro histórico de Arequipa. Con arquitectura tradicional arequipeña, patios internos y vista espectacular al volcán Misti. A pasos de la Plaza de Armas y principales atractivos turísticos.', 'No fumar en interiores. Mascotas no permitidas. Respetar el patrimonio histórico del inmueble.', '14:00', '11:00', 6, 3, 2, 4, null, null, TIMESTAMP '2025-11-25 00:41:42', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (51, 'Departamento moderno en Cayma con impresionante vista a los tres volcanes: Misti, Chachani y Pichu Pichu. Edificio nuevo con todas las comodidades, cerca de centros comerciales y restaurantes.', 'No se permiten mascotas. No fumar. Estacionamiento incluido.', '15:00', '12:00', 4, 2, 2, 2, null, null, TIMESTAMP '2025-11-25 00:42:27', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (52, 'Loft de diseño único en el tradicional distrito de Yanahuara. Combina arquitectura colonial con toques modernos. Cerca del mirador de Yanahuara y Carmen Alto. Perfecto para parejas o viajeros creativos.', 'Se permiten mascotas pequeñas. No fumar en interiores. Horario de silencio después de las 10 PM.', '14:00', '11:00', 3, 1, 1, 2, null, null, TIMESTAMP '2025-11-25 00:43:31', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (53, 'Hermosa casa campestre en Sabandía rodeada de naturaleza y con vista a los volcanes. Amplios jardines, zona de parrilla y piscina. Perfecta para familias o grupos que buscan tranquilidad cerca de la ciudad. A 20 minutos del centro.', 'Se permiten mascotas. No fumar en interiores. Capacidad máxima 8 personas.', '15:00', '12:00', 8, 4, 3, 5, null, null, TIMESTAMP '2025-11-25 00:43:50', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (54, 'Estudio funcional en Vallecito, ideal para estudiantes o profesionales. Cerca de la UNSA y UCSM. Incluye cocina equipada, internet de alta velocidad y zona de estudio. Excelente ubicación con transporte público.', 'No se permiten mascotas. No fumar. Check-in flexible.', '13:00', '11:00', 2, 1, 1, 1, null, null, TIMESTAMP '2025-11-25 00:44:11', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (55, 'Amplio departamento familiar en Selva Alegre, zona residencial tranquila. Edificio con seguridad, gimnasio y áreas verdes. Cerca de colegios, supermercados y parques. Ideal para familias o estadías prolongadas.', 'Se permiten mascotas pequeñas. No fumar. Uso de áreas comunes del edificio.', '14:00', '11:00', 5, 2, 2, 3, null, null, TIMESTAMP '2025-11-25 00:44:30', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (56, 'Casa de campo en el tradicional pueblo de Characato. Rodeada de campiña arequipeña, con huerto orgánico y animales de granja. Perfecta para desconectarse y disfrutar de la naturaleza. A 30 minutos de Arequipa.', 'Se permiten mascotas. No fumar en interiores. Ideal para familias con niños.', '15:00', '12:00', 7, 3, 2, 4, null, null, TIMESTAMP '2025-11-25 00:44:56', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (57, 'Apartamento moderno en zona comercial de Bustamante y Rivero. Rodeado de restaurantes, cafés, centros comerciales y supermercados. Edificio con seguridad 24/7 y estacionamiento. Ideal para viajeros de negocios o turistas.', 'No se permiten mascotas. No fumar. Estacionamiento incluido.', '14:00', '11:00', 3, 1, 1, 2, null, null, TIMESTAMP '2025-11-25 00:45:18', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (58, 'Loft de diseño minimalista en Cerro Colorado. Espacio abierto con decoración contemporánea y funcional. Cerca del aeropuerto y zona industrial. Perfecto para viajeros de negocios o estadías cortas.', 'No se permiten mascotas. No fumar. Check-in flexible.', '13:00', '11:00', 2, 1, 1, 1, null, null, TIMESTAMP '2025-11-25 00:45:29', null, null, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (83, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 18:47:20', null, 4, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (84, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 18:51:13', null, 4, null, null, null);
INSERT INTO SMART.PROPERTY_DETAILS (PROPERTY_ID, DESCRIPTION_LONG, HOUSE_RULES, CHECKIN_TIME, CHECKOUT_TIME, CAPACITY, BEDROOMS, BATHROOMS, BEDS, AREA_M2, FLOOR_NUMBER, CREATED_AT, UPDATED_AT, MAX_ADULTS, MAX_CHILDREN, MAX_BABY, MAX_PETS) VALUES (85, 'Espacioso departamento con vista al mar', 'No fumar. No fiestas.', '14:00', '12:00', 4, 2, 2, 2, 85.5, null, TIMESTAMP '2025-12-01 18:53:24', null, 4, null, null, null);
